title: Salman Soofi personal website
email: salmansoofi@gmail.com
description: >-
  This is the personal website of Salaman Soofi, a painter from Pakistan.
baseurl: ""
url: "https://cc.agordeev.com"
facebook:
  publisher: "https://www.facebook.com/salmansoofi313/"
twitter:
  card: summary
  username: salmansoofi
social:
  name: Salman Soofi
  links:
    - https://www.facebook.com/salmansoofi313/
    - https://www.linkedin.com/in/salman-soofi-21143415
    - https://www.instagram.com/salman_soofi_artist

permalink: pretty
google_maps_javascript_api_key: "AIzaSyCWIfKAPho7S3c_BQxb_JXZ6ePzCWyQg9A"
google_analytics_key: UA-175045385-1
collections_dir: collections
collections:
  exhibitions:
    _hide_content: true
  media:
    _hide_content: true

defaults:
  -
    scope:
      path: ""
      type: post
    values:
      layout: post
  -
    scope:
      path: ""
    values:
      image: /img/salman-twitter-card.jpg
      layout: page

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
