title: Salman Soofi personal website
email: salmansoofi@gmail.om
description: >-
  This is the personal website of Salaman Soofi, a painter from Pakistan.
baseurl:
url: "https://cc.agordeev.com"
logo: https://kulturologia.ru/media/avatar-24_s.jpg
facebook:
  publisher: "https://www.facebook.com/salmansoofi313/"
twitter:
  card: summary
  username: salmansoofi
social:
  name: Salman Soofi
  links:
    - https://www.facebook.com/salmansoofi313/
    - https://www.linkedin.com/in/salman-soofi-21143415
    - https://www.instagram.com/salman_soofi_artist

defaults:
  -
    scope:
      path: ""
    values:
      image: https://kulturologia.ru/media/avatar-24_s.jpg

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
