title: Salman Soofi personal website
email: salmansoofi@gmail.com
description: >-
  This is the personal website of Salaman Soofi, a painter from Pakistan.
baseurl: ""
url: "https://cc.agordeev.com"
facebook:
  publisher: "https://www.facebook.com/salmansoofi313/"
twitter:
  card: summary
  username: salmansoofi
social:
  name: Salman Soofi
  links:
    - https://www.facebook.com/salmansoofi313/
    - https://www.linkedin.com/in/salman-soofi-21143415
    - https://www.instagram.com/salman_soofi_artist

permalink: pretty
collections_dir: collections
defaults:
  -
    scope:
      path: ""
    values:
      image: /img/salman-twitter-card.jpg
      layout: page

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
